In [96]:
import pandas as pd
koi_df = pd.read_csv("../data/cumulative_2025.09.21_17.22.39.csv", skiprows=144)
koi_df.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_vet_stat,koi_vet_date,koi_pdisposition,koi_score,koi_fpflag_nt,...,koi_dicco_mdec,koi_dicco_mdec_err,koi_dicco_msky,koi_dicco_msky_err,koi_dikco_mra,koi_dikco_mra_err,koi_dikco_mdec,koi_dikco_mdec_err,koi_dikco_msky,koi_dikco_msky_err
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,Done,2018-08-16,CANDIDATE,1.000,0,...,0.200,0.160,0.200,0.170,0.080,0.130,0.310,0.170,0.320,0.160
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,Done,2018-08-16,CANDIDATE,0.969,0,...,0.000,0.480,0.390,0.360,0.490,0.340,0.120,0.730,0.500,0.450
2,3,10811496,K00753.01,NaN,CANDIDATE,Done,2018-08-16,CANDIDATE,0.000,0,...,-0.034,0.070,0.042,0.072,0.002,0.071,-0.027,0.074,0.027,0.074
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,Done,2018-08-16,FALSE POSITIVE,0.000,0,...,0.147,0.078,0.289,0.079,-0.257,0.072,0.099,0.077,0.276,0.076
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,Done,2018-08-16,CANDIDATE,1.000,0,...,-0.090,0.180,0.100,0.140,0.070,0.180,0.020,0.160,0.070,0.200

In [97]:
koi_df.shape

(9564, 141)

In [98]:
koi_df.describe()

,rowid,kepid,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,...,koi_dicco_mdec,koi_dicco_mdec_err,koi_dicco_msky,koi_dicco_msky_err,koi_dikco_mra,koi_dikco_mra_err,koi_dikco_mdec,koi_dikco_mdec_err,koi_dikco_msky,koi_dikco_msky_err
count,9564.000000,9.564000e+03,8054.000000,9564.000000,9564.000000,9564.000000,9564.000000,9564.000000,9110.000000,9110.000000,...,8965.000000,8965.000000,8965.000000,8965.000000,8994.000000,8994.000000,8994.000000,8994.000000,8994.000000,8994.000000
mean,4782.500000,7.690628e+06,0.480829,0.208595,0.232748,0.197512,0.120033,75.671358,0.002148,-0.002148,...,-0.045420,0.446229,1.866561,0.489930,-0.024244,0.425337,-0.076749,0.436684,1.812566,0.476060
std,2761.033321,2.653459e+06,0.476928,4.767290,0.422605,0.398142,0.325018,1334.744046,0.008236,0.008236,...,2.573558,0.569933,2.988742,0.646403,2.382286,0.602150,2.553758,0.567535,2.986376,0.647587
min,1.000000,7.574500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.241843,0.000000,-0.172500,...,-75.900000,0.067000,0.000000,0.067000,-27.800000,0.067000,-76.600000,0.067000,0.000000,0.067000
25%,2391.750000,5.556034e+06,0.000000,0.000000,0.000000,0.000000,0.000000,2.733684,0.000005,-0.000276,...,-0.387000,0.098000,0.170000,0.100000,-0.310000,0.087000,-0.390000,0.090000,0.210000,0.094000
50%,4782.500000,7.906892e+06,0.334000,0.000000,0.000000,0.000000,0.000000,9.752831,0.000035,-0.000035,...,0.000000,0.280000,0.610000,0.310000,-0.004000,0.250000,-0.017000,0.270000,0.583000,0.290000
75%,7173.250000,9.873066e+06,0.998000,0.000000,0.000000,0.000000,0.000000,40.715178,0.000276,-0.000005,...,0.300000,0.610000,2.160000,0.680000,0.290000,0.590000,0.300000,0.600000,1.970000,0.660000
max,9564.000000,1.293514e+07,1.000000,465.000000,1.000000,1.000000,1.000000,129995.778400,0.172500,0.000000,...,27.500000,22.000000,88.600000,32.000000,46.570000,33.000000,34.000000,22.000000,89.600000,32.000000

In [99]:
df = koi_df[['koi_period', 'koi_time0bk', 'koi_duration', 'koi_depth', 'koi_prad', 'koi_insol', 'koi_teq', 'koi_steff', 'koi_slogg', 'koi_srad', 'koi_disposition']]
df

,koi_period,koi_time0bk,koi_duration,koi_depth,koi_prad,koi_insol,koi_teq,koi_steff,koi_slogg,koi_srad,koi_disposition
0,9.488036,170.538750,2.95750,615.8,2.26,93.59,793.0,5455.0,4.467,0.927,CONFIRMED
1,54.418383,162.513840,4.50700,874.8,2.83,9.11,443.0,5455.0,4.467,0.927,CONFIRMED
2,19.899140,175.850252,1.78220,10829.0,14.60,39.30,638.0,5853.0,4.544,0.868,CANDIDATE
3,1.736952,170.307565,2.40641,8079.2,33.46,891.96,1395.0,5805.0,4.564,0.791,FALSE POSITIVE
4,2.525592,171.595550,1.65450,603.3,2.75,926.16,1406.0,6031.0,4.438,1.046,CONFIRMED
...,...,...,...,...,...,...,...,...,...,...,...
9559,0.527699,131.705093,3.22210,1579.2,29.35,4500.53,2088.0,5638.0,4.529,0.903,FALSE POSITIVE
9560,1.739849,133.001270,3.11400,48.5,0.72,1585.81,1608.0,6119.0,4.444,1.031,CANDIDATE
9561,0.681402,132.181750,0.86500,103.6,1.07,5713.41,2218.0,6173.0,4.447,1.041,FALSE POSITIVE
9562,333.486169,153.615010,3.19900,639.1,19.30,22.68,557.0,4989.0,2.992,7.824,CANDIDATE
9563,4.856035,135.993300,3.07800,76.7,1.05,607.42,1266.0,6469.0,4.385,1.193,FALSE POSITIVE

In [100]:
df['koi_disposition'].value_counts()

koi_disposition
FALSE POSITIVE    4839
CONFIRMED         2746
CANDIDATE         1979
Name: count, dtype: int64

In [101]:
df.columns

Index(['koi_period', 'koi_time0bk', 'koi_duration', 'koi_depth', 'koi_prad',
       'koi_insol', 'koi_teq', 'koi_steff', 'koi_slogg', 'koi_srad',
       'koi_disposition'],
      dtype='object')

In [102]:
df = df.rename(columns={
    'koi_period': 'orbital_period',
    'koi_time0bk': 'transit_epoch',
    'koi_duration': 'transit_duration',
    'koi_depth': 'transit_depth',
    'koi_prad': 'planet_radius',
    'koi_insol': 'insolation_flux',
    'koi_teq': 'equilibrium_temp',
    'koi_steff': 'effective_temp',
    'koi_slogg': 'surface_gravity',
    'koi_srad': 'stellar_radius',
    'koi_disposition': 'disposition'
})
df['dataset'] = 'KOI'
df

,orbital_period,transit_epoch,transit_duration,transit_depth,planet_radius,insolation_flux,equilibrium_temp,effective_temp,surface_gravity,stellar_radius,disposition,dataset
0,9.488036,170.538750,2.95750,615.8,2.26,93.59,793.0,5455.0,4.467,0.927,CONFIRMED,KOI
1,54.418383,162.513840,4.50700,874.8,2.83,9.11,443.0,5455.0,4.467,0.927,CONFIRMED,KOI
2,19.899140,175.850252,1.78220,10829.0,14.60,39.30,638.0,5853.0,4.544,0.868,CANDIDATE,KOI
3,1.736952,170.307565,2.40641,8079.2,33.46,891.96,1395.0,5805.0,4.564,0.791,FALSE POSITIVE,KOI
4,2.525592,171.595550,1.65450,603.3,2.75,926.16,1406.0,6031.0,4.438,1.046,CONFIRMED,KOI
...,...,...,...,...,...,...,...,...,...,...,...,...
9559,0.527699,131.705093,3.22210,1579.2,29.35,4500.53,2088.0,5638.0,4.529,0.903,FALSE POSITIVE,KOI
9560,1.739849,133.001270,3.11400,48.5,0.72,1585.81,1608.0,6119.0,4.444,1.031,CANDIDATE,KOI
9561,0.681402,132.181750,0.86500,103.6,1.07,5713.41,2218.0,6173.0,4.447,1.041,FALSE POSITIVE,KOI
9562,333.486169,153.615010,3.19900,639.1,19.30,22.68,557.0,4989.0,2.992,7.824,CANDIDATE,KOI
9563,4.856035,135.993300,3.07800,76.7,1.05,607.42,1266.0,6469.0,4.385,1.193,FALSE POSITIVE,KOI

In [103]:
df = df.drop(columns=['insolation_flux', 'equilibrium_temp'])
df

,orbital_period,transit_epoch,transit_duration,transit_depth,planet_radius,effective_temp,surface_gravity,stellar_radius,disposition,dataset
0,9.488036,170.538750,2.95750,615.8,2.26,5455.0,4.467,0.927,CONFIRMED,KOI
1,54.418383,162.513840,4.50700,874.8,2.83,5455.0,4.467,0.927,CONFIRMED,KOI
2,19.899140,175.850252,1.78220,10829.0,14.60,5853.0,4.544,0.868,CANDIDATE,KOI
3,1.736952,170.307565,2.40641,8079.2,33.46,5805.0,4.564,0.791,FALSE POSITIVE,KOI
4,2.525592,171.595550,1.65450,603.3,2.75,6031.0,4.438,1.046,CONFIRMED,KOI
...,...,...,...,...,...,...,...,...,...,...
9559,0.527699,131.705093,3.22210,1579.2,29.35,5638.0,4.529,0.903,FALSE POSITIVE,KOI
9560,1.739849,133.001270,3.11400,48.5,0.72,6119.0,4.444,1.031,CANDIDATE,KOI
9561,0.681402,132.181750,0.86500,103.6,1.07,6173.0,4.447,1.041,FALSE POSITIVE,KOI
9562,333.486169,153.615010,3.19900,639.1,19.30,4989.0,2.992,7.824,CANDIDATE,KOI
9563,4.856035,135.993300,3.07800,76.7,1.05,6469.0,4.385,1.193,FALSE POSITIVE,KOI